.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTORS.md
README.md

Looking to add some CONTRIBUTION guidelines and some issue templates to make it clearer how to jump in.

Contribution Guidelines and some templates for Issues/PRs.

---

pom.xml
src/main/java/org/sonatype/nexus/repository/r/internal/RDescriptionUtils.java

Just updates to 3.4.0-02, and I spotted an unneeded import, so that's gone now :)
* Pom update to 3.4.0-02
* Tidy in RDescriptionUtils.java
Build: http://bamboo.s/browse/NX3-RF5-1 ✔️

Update to 3.4.0-02 and tidy

---

pom.xml

Just a quick ditty to update to 3.5.0-02 since it is out
* Updates pom.xml, nothing major

Update to 3.5.0-02

---

README.md

This makes a small tweak to our README to help out potentially confused PRO users who can't figure out why R isn't loading :)
* Tweaks to README.md

Small tweak to help out users on Pro installs

---

pom.xml

[pom] Bumped to 3.5.1-02

---

README.md

nexus-oss-feature-3.x.y-features.xml file has a different format

[README] Updated to support new format file from 3.5.1-02

---

.github/CONTRIBUTING.md
.travis.yml
README.md

This starts a POC of using TravisCI to build this project externally.
* Adds `.travis.yml`

Initial Travis Commit

---

pom.xml

Just a quick version update to use 3.9.0-01 for Nexus plugins
* Updates `pom.xml`
`mvn clean package` builds clean

Update Nexus version to 3.9.0-01

---

pom.xml

Updates to use 3.10.0-04 
* Changes to `pom.xml`

Update to 3.10

---

docs/R_USER_DOCUMENTATION.md

* Link adjustments
** Some text adjustments to reflect what the (new) links show
* Typo fix

Doc adjust

---

README.md
pom.xml

Welp, a new version, a new update :)
* Updates `pom.xml`
* Small `README.md` updates
It relates to the following issue #s:
* Fixes #43

Update to Newest Version (3.14.0-04)

---

nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RHostedIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RITSupport.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RProxyIT.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RComponentMaintenance.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RRecipeSupport.groovy

https://issues.sonatype.org/browse/NEXUS-20711
https://issues.sonatype.org/browse/NEXUS-20714

NEXUS-20711: Component not removed with asset fix

---

README.md

* updated instructions to include a `easiest install` option

updated install instructions to include a `easiest install`

---

nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RGroupRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RHostedRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RProxyRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RRecipeSupport.groovy
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/RRecipeTest.java

https://issues.sonatype.org/browse/NEXUS-20442

NEXUS-20442: HA support

---

nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RClient.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RGroupIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RHostedIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RProxyIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/cleanup/CleanupTaskRIT.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/HostedHandlers.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RGroupRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RHostedRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RProxyRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RRecipeSupport.groovy

https://issues.sonatype.org/browse/NEXUS-21222

NEXUS-21222: Filter R upload files

---

nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RHostedIT.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/HostedHandlers.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RHostedRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RRecipeSupport.groovy

https://issues.sonatype.org/browse/NEXUS-21194

NEXUS-21194: Metadata not supported handler

---

nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RFacetImpl.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RFacetUtils.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/RFacetUtilsTest.java

https://issues.sonatype.org/browse/NEXUS-21552

NEXUS-21552: Add component group to findComponent() method

---

nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/HostedHandlers.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RPathUtils.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/upload/RUploadHandler.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/upload/RUploadHandlerTest.java

https://issues.sonatype.org/browse/NEXUS-21549

NEXUS-21549: Validation for UI upload

---

nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/HostedHandlers.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RHostedRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RPathUtils.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RProxyFacetImpl.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/upload/RUploadHandler.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/HostedHandlersTest.java

https://issues.sonatype.org/browse/NEXUS-21534

NEXUS-21534: Refactoring

---

nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RHostedIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RITSupport.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/HostedHandlers.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/PackageValidator.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RHostedRecipe.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RPathUtils.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/RRecipeSupport.groovy
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/upload/RUploadHandler.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/HostedHandlersTest.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/upload/RUploadHandlerTest.java

https://issues.sonatype.org/browse/NEXUS-21588

NEXUS-21588: Improve upload error message

---

nexus-repository-r-it/pom.xml
nexus-repository-r/pom.xml
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/hosted/RHostedFacetImpl.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/hosted/RPackagesBuilder.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/hosted/RHostedFacetImplTest.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/hosted/RPackagesBuilderFacetImplTest.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/hosted/RPackagesBuilderTest.java
nexus-restore-r/pom.xml

https://issues.sonatype.org/browse/NEXUS-21688

NEXUS-21688: Merge master into feature branch

---

nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/internal/util/PackageValidator.java

https://issues.sonatype.org/browse/NEXUS-21690

NEXUS-21690: Change upload error message in R hosted

---

.circleci/config.yml
.maven.xml
pom.xml

WIP - Initial changes to test using new Orb to do releases via maven-release-plugin.

changes to test release with dryRun

---

.circleci/config.yml

Update ssh to enable release in the circle ci.

update ssh finger-print

---

pom.xml

https://issues.sonatype.org/browse/NEXUS-22599

NEXUS-22599:  Update NXRM parent version for release

---

Dockerfile
README.md

This is a work-in-progress branch to illustrate a simpler Dockerfile. However, it requires a newer version of Nexus Repository Manager be the parent before it will work.
The most useful file in this branch is the Dockerfile, and maybe some of the README changes.
I just had a simpler thought: I you include the Dockerfile from this PR and some related README changes in your development branch, then feel free to close out this PR. :)

Docker2, needs newer NXRM

---

pom.xml

https://issues.sonatype.org/browse/NEXUS-23275

NEXUS-23275: NXRM 3.22 Support

---

nexus-repository-r-it/pom.xml
nexus-repository-r/pom.xml
nexus-restore-r/pom.xml
pom.xml

Increase the project version. To pass release automation

Bump project version

---

nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RGroupIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RHostedIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RITConfig.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RITSupport.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RProxyIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/RRoutingRuleIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/cleanup/CleanupTaskRIT.java
nexus-repository-r-it/src/test/java/org/sonatype/nexus/plugins/r/internal/restore/RRestoreBlobIT.java
nexus-repository-r/src/test/java/org/sonatype/nexus/repository/r/internal/util/RFacetUtilsTest.java
pom.xml

Ticket: https://issues.sonatype.org/browse/NEXUS-24318
#128  PR is cherry-picked to current PR 133. so 128 could be closed after  133 PR merge to master.

NEXUS-24318: Aligned R ITs with renewed IT infrastructure

---

nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RGroupRepositoriesApiResource.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RGroupRepositoriesApiResourceBeta.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RGroupRepositoriesApiResourceV1.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RHostedRepositoriesApiResource.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RHostedRepositoriesApiResourceBeta.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RHostedRepositoriesApiResourceV1.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RProxyRepositoriesApiResource.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RProxyRepositoriesApiResourceBeta.java
nexus-repository-r/src/main/java/org/sonatype/nexus/repository/r/rest/RProxyRepositoriesApiResourceV1.java

ticket: https://issues.sonatype.org/browse/NEXUS-24905
tested manually. REST API was not broken and works properly.

fix broken rest api
